// tools/winscope-ng/src/app/components/app.component.ts
/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Component, Injector, Inject, ViewEncapsulation, Input } from "@angular/core";
import { createCustomElement } from "@angular/elements";
import { TraceCoordinator } from "../trace_coordinator";
import { proxyClient, ProxyState } from "trace_collection/proxy_client";
import { PersistentStore } from "common/persistent_store";
import { ViewerWindowManagerComponent } from "viewers/viewer_window_manager/viewer_window_manager.component";
import { ViewerSurfaceFlingerComponent } from "viewers/viewer_surface_flinger/viewer_surface_flinger.component";
import { Timestamp } from "common/trace/timestamp";
import { MatSliderChange } from "@angular/material/slider";
import { ViewerInputMethodComponent } from "viewers/components/viewer_input_method.component";

@Component({
  selector: "app-root",
  template: `
    <mat-toolbar class="app-toolbar">
      <span id="app-title">Winscope</span>
      <span class="toolbar-wrapper">
        <button mat-stroked-button *ngIf="dataLoaded" (click)="toggleTimestamp()">Start/End Timestamp</button>
        <button class="upload-new-btn" mat-stroked-button *ngIf="dataLoaded" (click)="clearData()">Upload New</button>
      </span>
    </mat-toolbar>

    <div class="welcome-info" *ngIf="!dataLoaded">
      <span>Welcome to Winscope. Please select source to view traces.</span>
    </div>

    <div *ngIf="!dataLoaded" fxLayout="row wrap" fxLayoutGap="10px grid" class="card-grid">
      <mat-card class="homepage-card" id="collect-traces-card">
        <collect-traces [traceCoordinator]="traceCoordinator" (dataLoadedChange)="onDataLoadedChange($event)"[store]="store"></collect-traces>
      </mat-card>
      <mat-card class="homepage-card" id="upload-traces-card">
        <upload-traces [traceCoordinator]="traceCoordinator" (dataLoadedChange)="onDataLoadedChange($event)"></upload-traces>
      </mat-card>
    </div>

    <div id="viewers" [class]="showViewers()">
      <trace-view
      [store]="store"
      [traceCoordinator]="traceCoordinator"
      ></trace-view>
    </div>

    <div id="timescrub">
      <mat-slider
        *ngIf="dataLoaded"
        step="1"
        min="0"
        [max]="this.allTimestamps.length-1"
        aria-label="units"
        [value]="currentTimestampIndex"
        (input)="updateCurrentTimestamp($event)"
        class="time-slider"
      ></mat-slider>
    </div>
    <div id="timestamps">
    </div>
  `,
  styles: [
    `
      .time-slider {
        width: 100%
      }
      .upload-new-btn {
        float: right;
        position: relative;
        vertical-align: middle;
        display: inline-block;
      }
      .app-toolbar {
        border-bottom: 1px solid var(--default-border);
        box-shadow: none;
        background-color: rgba(1, 1, 1, 0);
        height: 56px;
        vertical-align: middle;
        position: relative;
        display: inline-block;
      }
      .toolbar-wrapper {
        width: 100%;
        height: 100%;
        vertical-align: middle;
        position: relative;
        display: inline-block;
        align-content: center;
      }
      .welcome-info {
        text-align: center;
        font: inherit;
        padding: 40px;
      }
    `
  ],
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {
  title = "winscope-ng";
  traceCoordinator: TraceCoordinator;
  states = ProxyState;
  store: PersistentStore = new PersistentStore();
  currentTimestamp?: Timestamp;
  currentTimestampIndex = 0;
  allTimestamps: Timestamp[] = [];
  @Input() dataLoaded = false;

  constructor(
    @Inject(Injector) injector: Injector
  ) {
    this.traceCoordinator = new TraceCoordinator();
    if (!customElements.get("viewer-window-manager")) {
      customElements.define("viewer-window-manager",
        createCustomElement(ViewerWindowManagerComponent, {injector}));
    }
    if (!customElements.get("viewer-surface-flinger")) {
      customElements.define("viewer-surface-flinger",
        createCustomElement(ViewerSurfaceFlingerComponent, {injector}));
    }
    if (!customElements.get("viewer-input-method")) {
      customElements.define("viewer-input-method",
        createCustomElement(ViewerInputMethodComponent, {injector}));
    }
  }

  public updateCurrentTimestamp(event: MatSliderChange) {
    if (event.value) {
      this.currentTimestampIndex = event.value;
      this.notifyCurrentTimestamp();
    }
  }

  public toggleTimestamp() {
    if (this.currentTimestampIndex===0) {
      this.currentTimestampIndex = this.allTimestamps.length-1;
    } else {
      this.currentTimestampIndex = 0;
    }
    this.notifyCurrentTimestamp();
  }

  public clearData() {
    this.dataLoaded = false;
    this.traceCoordinator.clearData();
    proxyClient.adbData = [];
  }

  public showViewers() {
    const isShown = this.dataLoaded ? "show" : "hide";
    return `viewers ${isShown}`;
  }

  public onDataLoadedChange(dataLoaded: boolean) {
    if (dataLoaded && !(this.traceCoordinator.getViewers().length > 0)) {
      this.allTimestamps = this.traceCoordinator.getTimestamps();
      this.traceCoordinator.createViewers();
      this.currentTimestampIndex = 0;
      this.notifyCurrentTimestamp();
      this.dataLoaded = dataLoaded;
    }
  }

  private notifyCurrentTimestamp() {
    this.currentTimestamp = this.allTimestamps[this.currentTimestampIndex];
    this.traceCoordinator.notifyCurrentTimestamp(this.currentTimestamp);
  }
}

// tools/winscope/src/App.vue
<!-- Copyright (C) 2017 The Android Open Source Project

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<template>
  <div id="app">
    <md-app>
      <md-app-toolbar md-tag="md-toolbar">
        <h1 class="md-title" style="flex: 1">{{title}}</h1>
        <md-button
          class="md-accent md-raised md-theme-default"
          @click="clear()"
          v-if="dataLoaded"
        >Clear</md-button>
      </md-app-toolbar>

      <md-app-content class="main-content">
        <div class="md-layout m-2" v-if="!dataLoaded">
          <dataadb ref="adb" :store="store" @dataReady="onDataReady" @statusChange="setStatus" />
          <datainput ref="input" :store="store" @dataReady="onDataReady" @statusChange="setStatus" />
        </div>
        <dataview
          v-for="file in files"
          :key="file.filename"
          :ref="file.filename"
          :store="store"
          :file="file"
          @click="onDataViewFocus(file)"
        />

        <bottom-navigation
          :files="files"
          :activeFile="activeFile"
          :video="video"
          :store="store"
          :ref="bottomNavRef"
          v-if="dataLoaded"
        />
      </md-app-content>
    </md-app>
  </div>
</template>
<script>
import TreeView from './TreeView.vue'
import BottomNavigation from './BottomNavigation.vue'
import Rects from './Rects.vue'
import DataView from './DataView.vue'
import DataInput from './DataInput.vue'
import LocalStore from './localstore.js'
import DataAdb from './DataAdb.vue'
import FileType from './FileType.js'

const APP_NAME = "Winscope"

export default {
  name: 'app',
  mixins: [FileType],
  data() {
    return {
      files: [],
      video: null,
      title: APP_NAME,
      activeFile: null,
      activeDataView: null,
      store: LocalStore('app', {
        flattened: false,
        onlyVisible: false,
        displayDefaults: true,
      }),
      bottomNavRef: "bottomNav",
    }
  },
  created() {
    window.addEventListener('keydown', this.onKeyDown);
    window.addEventListener('scroll', this.onScroll);
    document.title = this.title;
  },
  destroyed() {
    window.removeEventListener('keydown', this.onKeyDown);
    window.removeEventListener('scroll', this.onScroll);
  },
  methods: {
    clear() {
      this.files.forEach(function(item) { item.destroy(); })
      this.files = [];
      this.activeDataView = null;
    },
    onDataViewFocus(file) {
      this.activeFile = file;
      this.activeDataView = file.filename;
    },
    onKeyDown(event) {
      event = event || window.event;
      if (event.keyCode == 37 /* left */ ) {
        this.$refs[this.bottomNavRef].advanceTimeline(-1);
      } else if (event.keyCode == 39 /* right */ ) {
        this.$refs[this.bottomNavRef].advanceTimeline(1);
      } else if (event.keyCode == 38 /* up */ ) {
        this.$refs[this.activeView][0].arrowUp();
      } else if (event.keyCode == 40 /* down */ ) {
        this.$refs[this.activeView][0].arrowDown();
      } else {
        return false;
      }
      event.preventDefault();
      return true;
    },
    onDataReady(files) {
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        if (this.isVideo(file)) {
          this.video = file;
        }
        this.files.push(file);
      }
    },
    setStatus(status) {
      if (status) {
        this.title = status;
      } else {
        this.title = APP_NAME;
      }
    },
  },
  computed: {
    prettyDump: function() { return JSON.stringify(this.dump, null, 2); },
    dataLoaded: function() { return this.files.length > 0 },
    activeView: function() {
      if (!this.activeDataView && this.files.length > 0) {
        this.activeDataView = this.files[0].filename;
      }
      return this.activeDataView;
    },
  },
  watch: {
    title() {
      document.title = this.title;
    }
  },
  components: {
    'bottom-navigation': BottomNavigation,
    'dataview': DataView,
    'datainput': DataInput,
    'dataadb': DataAdb,
  }
};
</script>
<style>
#app .md-app-container {
  transform: none!important; /* Get rid of tranforms which prevent fixed position from being used */
}

.main-content {
  padding-bottom: 75px;
}

.main-content>* {
  margin: 1em;
}

.card-toolbar {
  border-bottom: 1px solid rgba(0, 0, 0, .12);
}

.timeline {
  margin: 16px;
}

.container {
  display: flex;
  flex-wrap: wrap;
}

.md-button {
  margin-top: 1em
}

h1,
h2 {
  font-weight: normal;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}
</style>
